apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::523715909084:role/UdacityFlaskDeployCBKubectlRole
      username: build 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::523715909084:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1DZSFBBJPUECP
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-26T00:02:42Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-06-26T00:02:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2039"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 72597a18-f408-4a95-ba3a-446739c57de0
